---
name: Package Frontend Docker Image

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
      - ".github/workflows/package-devcontainer-docker-image.yml"

jobs:
  build-and-push-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          VERSION=$(date +%y.%m.%d.%H.%M)
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Normalize repository name
        id: repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Validate Dockerfile exists
        run: |
          test -f ".devcontainer/Dockerfile" || (echo "Dockerfile not found in .devcontainer/" && exit 1)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push DevContainer image
        uses: docker/build-push-action@v5
        with:
          context: ./.devcontainer
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}
          tags: |
            ghcr.io/${{ steps.repo.outputs.name }}-devcontainer:${{ steps.version.outputs.tag }}
            ghcr.io/${{ steps.repo.outputs.name }}-devcontainer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ steps.repo.outputs.name }}-devcontainer:${{ steps.version.outputs.tag }}
          format: spdx-json
          upload-release-assets: false
          artifact-name: sbom-devcontainer-${{ steps.version.outputs.tag }}
